name: klassensysteem
version: '1.20.1'
main: me.marc3308.klassensysteem.Klassensysteem
api-version: '1.20'

commands:
  profil:
    description: opens up your provile
  klasse:
    description: command manager
  skilltree:
    description: opens your skilltree
  partyeinladung:
    description: opens a inv if you are invitet to a party

permissions:
  klassenmod:
    description: du kannst dir proviele anderer spieler angucken, jemandem xp geben/nehmen und lv ändern
  got:
    description: Du bist got
